### ISSUE TITLE
monogame version

### ISSUE THREAD

**Issue by ghost** [BlizzCrafter/MonoGame.Forms#39]
Hi

Is this code using the installed monogame package of my .net environment?
I'm now using monogame 3.8

**Comment by monogamefan** [comment]
is it possible to update the package to monogame 3.8?

**Comment by BlizzCrafter** [comment]
Easily possible now with MonoGame.Forms.3.0.0 - just update the nuget package of [MonoGame.Framework.WindowsDX.9000](https://www.nuget.org/packages/MonoGame.Framework.WindowsDX.9000/).

If you install the new version of [MonoGame.Forms](https://www.nuget.org/packages/MonoGame.Forms.DX/3.0.0) this step is not needed, because the newest version is already included.
