### ISSUE TITLE
latest monogame

### ISSUE THREAD

**Issue by ghost** [BlizzCrafter/MonoGame.Forms#41]
Hello

Is it possible monogame forms can be used with latest monogame 3.8.1 and using .net 6.0 or are we always forced to use the modified monogame version as we can read in the docs?

**Comment by BlizzCrafter** [comment]
Hey,

yes you need the modified version, otherwise you would need to compile the MonoGame.Framework from source and do compatibility patches for MonoGame.Forms by yourself (e.g. Mouse & Keyboard input and many more things). But I don't recommend that. You should use and update the already modified MonoGame version **only.**
