### ISSUE TITLE
Freeze while clicking/moving the title bar

### ISSUE THREAD

**Issue by Elem8100** [BlizzCrafter/MonoGame.Forms#46]
Lost game's Update( )
Currently each time you click or hold the mouse button or drag the title bar the window will freeze

**Comment by BlizzCrafter** [comment]
When dragging a Windows Forms control, the control’s update mechanism is temporarily suspended to prevent unnecessary updates during the drag operation. This is a default behavior in Windows Forms and ensures a performant application.

Additionally it only happens when clicking or dragging the title bar from my experience. So this shouldn't be a problem.

Sorry for the late reply. If you are feeling that this is still relevant then feel free to reopen this issue.
